- hosts: all
  become: true

  tasks:
  - name: create directories
    file:
      dest: /var/www/{{app.environment}}/{{app.name}}/{{item}}
      state: directory
      owner: "{{nginx.user}}"
      group: "{{nginx.user}}"
      mode: "g+rws"
      recurse: true
    loop:
    - releases
    - shared
    - shared/config
    - shared/log
    - shared/pids
    - shared/scripts
    - shared/sockets
    - shared/tmp
    - shared/backup
    - shared/bundle
    - shared/backup/models
