- hosts: all

  tasks:
  - name: install app ruby
    shell: /usr/local/rvm/bin/rvm install {{app.ruby}}

  - name: create {{app.ruby}}@{{app.name}}_{{app.environment}} gemset
    shell: "/usr/local/rvm/bin/rvm {{app.ruby}} do rvm gemset create {{app.name}}_{{app.environment}}"

  - name: install bundler
    shell: "/usr/local/rvm/bin/rvm {{app.ruby}}@{{app.name}}_{{app.environment}} do gem install bundler"
