- hosts: all
  become: true

  tasks:
  - name: check nginx installed
    stat:
      path: /etc/nginx/sites-available
    register: nginx_installed

  - name: trash /var/www/html
    file:
      state: absent
      path: /var/www/html

  - name: install production nginx puma virtualhost file
    template:
      src: "{{inventory_dir}}/files/app/nginx/puma/nginx_production.virtualhost"
      dest: /etc/nginx/sites-available/{{app.environment}}/{{app.name}}.conf
      owner: "root"
      group: "root"
      mode: 0644
    when: nginx_installed.stat.exists == true and app.environment == 'production'

  - name: symlink nginx virtualhost file
    file:
      src: /etc/nginx/sites-available/{{app.environment}}/{{app.name}}.conf
      dest: /etc/nginx/sites-enabled/{{app.environment}}/{{app.name}}.conf
      state: link
    when: nginx_installed.stat.exists == true

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    ignore_errors: true
