- hosts: all
  become: true

  tasks:
  - name: create /etc/nginx/sites-available directories
    file:
      dest: /etc/nginx/sites-available/{item}
      state: directory
      owner: "{{nginx.user}}"
      group: "{{nginx.user}}"
      mode: 0775
      recurse: true
    loop:
    - production
    - staging
    - develop
    - services

  - name: create /etc/nginx/sites-enabled directories
    file:
      dest: /etc/nginx/sites-enabled/production
      state: directory
      owner: "{{nginx.user}}"
      group: "{{nginx.user}}"
      mode: 0775
      recurse: true
    loop:
    - production
    - staging
    - develop
    - services
