- hosts: all
  become: true
  ignore_errors: true

  tasks:
  - name: update cache
    shell: apt-get update

  - name: chown /home/{{user}}
    file:
      dest: /home/{{user}}
      owner: "{{user}}"
      recurse: yes

  - name: create src tmp dir
    file:
      path: /home/{{user}}/tmp
      state: directory
      owner: "{{user}}"

  - name: run updatedb
    shell: updatedb

  - name: install applications
    apt:
      name: {{item}}
      state: present
      update_cache: true
    loop:
    - git
    - git-core
    - curl
    - python-passlib
    - python-pip
    - python-dev
    - apt-transport-https
    - acl
    - build-essential
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - libffi-dev
    - libncurses-dev
    - sqlite3
    - libsqlite3-dev
    - mlocate
    - aptitude
    - python-dev
    - libfreetype6-dev
    - python-pip3
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libwebp-dev
